# coding: utf-8

"""
    API для работы с файловыми ресурсами контента 

    Получение стриминг ссылок, загрузка данных в хранилище и отправка данных в облачные s3 хранилища  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import file_storage_api
from file_storage_api.api.task_api import TaskApi  # noqa: E501
from file_storage_api.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_task_api_v1_download_file_post(self):
        """Test case for download_task_api_v1_download_file_post

        Добавление информации о местонахождении файла  # noqa: E501
        """
        pass

    def test_upload_task_api_v1_upload_file_post(self):
        """Test case for upload_task_api_v1_upload_file_post

        Добавление информации о местонахождении файла  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
