# coding: utf-8

# flake8: noqa

"""
    API для работы с файловыми ресурсами контента 

    Получение стриминг ссылок, загрузка данных в хранилище и отправка данных в облачные s3 хранилища  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from file_storage_api.api.file_location_api import FileLocationApi
from file_storage_api.api.health_api import HealthApi
from file_storage_api.api.task_api import TaskApi
from file_storage_api.api.url_api import UrlApi
# import ApiClient
from file_storage_api.api_client import ApiClient
from file_storage_api.configuration import Configuration
# import models into sdk package
from file_storage_api.models.cdn import CDN
from file_storage_api.models.file_location import FileLocation
from file_storage_api.models.http_validation_error import HTTPValidationError
from file_storage_api.models.validation_error import ValidationError
